# -*- coding: utf-8 -*-
"""OSMI Survey Analysis for Predicting Mental Health in the Tech Industry.-LuisTorres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBOSsgLo_yl59ak0xkcQMunsHqEcKELl

# **OSMI Survey Analysis for Predicting Mental Health in the Tech Industry.**
*   **Name:** Luis Esteban Torres Perdomo


---


# 1.Introduction

Mental health of employees has emerged as a crucial aspect in organizations where the mental stress, pressure, and a high-productivity culture can lead to emotional instability. The World Health Organization has described mental health as an optimal state that allows an individual to cope with the usual demands of life, grow in their occupation, and become actively engaged in the social environment (World Health Organization, 2022). However, some results show that factors such as chronic work stress, overloading of work, or lack of institutional support have adverse effects on such status (Harnois and Gabriel, 2002).

Despite the efforts to de-stigmatize mental health, one of the strongest barriers to seeking help continues to exist, perpetuated to some degree by the perceptions of judgment, discrimination, or job-related consequences. Machine learning holds a methodological solution to help predict help-seeking in this regard. Such technology holds the ability to generate predictive models to deal with large data sets and detect subtle relationships between individual, organizational, and behavioral factors (Shatte et al., 2019).

Open Sourcing Mental Illness (OSMI, 2023) is a non-profit organization whose mission is to encourage education and support for mental illness across tech communities. OSMI has been conducting anonymous surveys of technology workers on matters of mental health at their workplaces for several years.

This project proposes using a machine learning model based on real surveys carried out by OSMI to create an analytical framework that helps in understanding and predicting the behaviors of employees about their mental well-being, such that other companies can take action to help their employees. In addition to helping identify meaningful patterns, this approach generates meaningful knowledge for organizations that wish to establish evidence-informed prevention and early intervention strategies.

---


# 2.Objective

Train a supervised machine learning algorithm to estimate the likelihood of an employee needing mental health treatment based on professional and personal profile information collected through OSMI surveys.

### 2.1 Specific objectives:
- Study real data of mental health within a technological environment.
- Clean and transform the data for analysis.
- Train multiple supervised models.
- Analyze their performance using tools such as GridSearchCV and metrics such as Accuracy and ROC-AUC.
- Make inferences and draw actionable conclusions.

---

# 3. Data Source

The datas set is the public sources of Kaggle.com and the link of datasource is : https://www.kaggle.com/code/megha1703/eda-and-hypothesis-testing-mental-health
(Osmi , 2023)


---

# 4. Data Exploration

First, the project's required libraries were imported, and proceeded to load the data was loaded and began exploring.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder , MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score , roc_curve, auc

df = pd.read_csv("/content/survey.csv")
df= df.copy()
df_random = df.sample(5)
df_random

data_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Missing Values': df.isnull().sum(),
    'Unique Values': df.nunique()
})
print(data_summary)

"""It was found that there were some NaN records within the project, and columns that were not required for the project were also identified. Therefore, the following actions were taken to the dataset to improve its performance.

-  Drop unused columns:
"""

df.drop(columns=['comments', 'state', 'Timestamp','Country'], inplace=True, errors='ignore')

"""- Normalize column Gender:"""

male_labels = ["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man", "msle", "mail", "malr", "cis man", "cis male"]
female_labels = ["cis female", "f", "female", "woman", "femake", "female ", "cis-female/femme", "female (cis)", "femail"]
trans_labels = ["trans-female", "something kinda male?", "queer/she/they", "non-binary", "nah", "all", "enby", "fluid", "genderqueer", "androgyne", "agender", "male leaning androgynous", "guy (-ish) ^_^", "trans woman", "neuter", "female (trans)", "queer", "ostensibly male, unsure what that really means"]
def simplify_gender(value):
    value = str(value).lower().strip()
    if value in male_labels:
        return 'Male'
    elif value in female_labels:
        return 'Female'
    elif value in trans_labels:
        return 'Trans'
    else:
        return 'other'
df['Gender'] = df['Gender'].apply(simplify_gender)

"""- Replace the missing values with the mean for numerical data and the mode for categorical data.

"""

df['work_interfere'] = df['work_interfere'].fillna(df['work_interfere'].mode()[0])
df['self_employed'] = df['self_employed'].fillna(df['self_employed'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].median())

df_random = df.sample(5)
df_random

data_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Missing Values': df.isnull().sum(),
    'Unique Values': df.nunique()
})
print(data_summary)

"""---
## 5 . Preprocessing

The data was prepared for correct use in the different models.

- The dependent (treatment) and independents variables are separated.
"""

y = df['treatment'].map({'Yes': 1, 'No': 0})
X = df.drop('treatment', axis=1)

"""A preprocessor with two parallel transformations is created:
- Numerical columns are standardised with StandardScaler (mean = 0, standard
deviation = 1).
- Categorical columns are encoded with OneHotEncoder, transforming them into binary variables.

"""

categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
])

"""- The data is divided into training (80%) and test (20%)."""

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

"""---


# 6. Model Training and Comparison

- Five supervised models were selected for comparison and selection of the best model for the project.
"""

models = {
    'Support Vector Machine': SVC(probability=True),
    'Decision Tree': DecisionTreeClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
     'Random Forest': RandomForestClassifier(random_state=42),
    'Logistic Regression': LogisticRegression(max_iter=1000),
}

"""- For each model a set of hyperparameters is defined which will be searched using GridSearchCV."""

params = {
    'Support Vector Machine': {'classifier__C': [1], 'classifier__kernel': ['rbf']},
    'Decision Tree': {'classifier__max_depth': [5, 10]},
    'Gradient Boosting': {'classifier__n_estimators': [100], 'classifier__learning_rate': [0.1]},
     'Random Forest': {'classifier__n_estimators': [100], 'classifier__max_depth': [10]},
    'Logistic Regression': {'classifier__C': [0.1, 1], 'classifier__solver': ['lbfgs']}
}

"""
- GridSearchCV with cross-validation (cv=5) is used to evaluate each combination
of parameters.
- The models are trained and compared.
- The accurrancy and ROC-AUC were taken into account to select the best project.
"""

accuracy_scores = {}
roc_auc_scores = {}
best_models = {}

for name, model in models.items():
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', model)
    ])
    grid = GridSearchCV(pipeline, params[name], cv=5, scoring='roc_auc')
    grid.fit(X_train, y_train)

    best_models[name] = grid.best_estimator_
    y_pred = grid.predict(X_test)
    y_proba = grid.predict_proba(X_test)[:, 1]

    accuracy_scores[name] = accuracy_score(y_test, y_pred)
    print(f"Accuracy - {name}: {accuracy_scores[name]:.4f}")
    roc_auc_scores[name] = roc_auc_score(y_test, y_proba)
    print(f"ROC-AUC - {name}: {roc_auc_scores[name]:.4f}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print()

plt.barh(list(accuracy_scores.keys()), list(accuracy_scores.values()))
plt.title("Model Accuracy")
plt.show()

plt.barh(list(roc_auc_scores.keys()), list(roc_auc_scores.values()), color='orange')
plt.title("Model ROC-AUC")
plt.show()

best_model_name = max(roc_auc_scores, key=roc_auc_scores.get)
final_model = best_models[best_model_name]
print("Best Model:", best_model_name)

"""---


##7. Evaluation of the Best Model(Logistic Regression)

**Logistic Regression** was selected as the final model because of its ROC-AUC(0.8073) score, which indicates superior overall classification performance, particularly in distinguishing between the two classes.
"""

y_pred_final = final_model.predict(X_test)
y_proba_final = final_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_final))
print("Accuracy:", accuracy_score(y_test, y_pred_final))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_final))

fpr, tpr, thresholds = roc_curve(y_test, y_proba_final)
roc_auc = auc(fpr, tpr)
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid()
plt.show()

"""This ROC curve plotted reflects the true positive rate and the false positive rate for different classification thresholds . The implication is that the model has an 81% chance of discriminating correctly between an individual who will receive treatment and one who will not."""

sns.heatmap(confusion_matrix(y_test, y_pred_final), annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()

"""Furthermore, with this graph, we confirm that the model was correct in most of its predictions, but it is not perfect, as it misinterprets people who do not receive assistance as receiving it, and vice versa.
Overall, performance is good, and the model is robust enough to be used as a decision-support tool.
"""

model = final_model.named_steps['classifier']
features = final_model.named_steps['preprocessor'].transformers_[1][1].get_feature_names_out(categorical_cols)
feature_names = np.concatenate([numerical_cols, features])
coefficients = pd.Series(model.coef_[0], index=feature_names)
plt.figure(figsize=(10, 8))
coefficients.sort_values(ascending=False).plot(kind='barh')
plt.title('Feature Importance (Logistic Regression Coefficients)')
plt.xlabel('Coefficient Value')
plt.grid()
plt.tight_layout()
plt.show()

"""Additionally, here we can see which variables have the greatest influence on interpretation. For example, traits such as work_interference_Oft, family_history_Yes, and coworkers_Yes have the highest values. In other words,  those who experience a lot of work interference because of mental health, have a family history, or are open with their coworkers are more likely to seek help. In contrast, features such as Gender_Male or seek_help_No are associated with a lower probability of seeking help.

This delineation not only strengthens our conceptual understanding of the model but also provides applied data for intervention and communication campaigns in workplace environments, according to the factors most influential on treatment-seeking behavior

---
# 7. Prediction for news records

In this section we enter 2 new records to validate the functioning of the preconditions of our project.
"""

person_1 = [41,'Female','No','No', 'Often', '100-500', 'Yes', 'No', 'Yes', 'Not sure', 'No','No','No','Somewhat easy','No','No','No','No','Yes','Yes','Yes','No']
person_2 = [41,'Male','No','No', 'Never', '26-100', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes','Yes','Yes','Very easy','No','No','Yes','Yes','No','No','No','No']
columnas = df.drop('treatment', axis=1).columns
new_data = pd.DataFrame([person_1, person_2], columns=columnas)
pred = final_model.predict(new_data)
proba = final_model.predict_proba(new_data)
pred = final_model.predict(new_data)
prob = final_model.predict_proba(new_data)

for i, (pred, prob) in enumerate(zip(pred, prob), start=1):
    resultado = 'Yes' if pred == 1 else 'No'
    print(f"Prediction {i}: Will seek treatment? {resultado} | Probability: {prob[1]:.2%}")

"""---

# 8. Conclusion
- The logistic regression model was the most suitable for the project.
Gradient Boosting and Support Vector Machine were also excellent, suggesting that more than one model can be used depending on the usage context.

- Family history, interference with work because of mental health frequency, employer benefits, and perceived anonymity upon treatment were the most important predictor variables.

- The prediction model can be utilized by HR and welfare personnel to identify employees who would require early contact with mental health.

**Limitations:**

- The results are self-reporting and drawn from voluntary questionnaires, the potential source of a bias.
- They might be not generalizable across all parts or company culture.
Some behavioural or psychological controlling variables have remained unquantified.

**Future research:**

- Improve the model using further longitudinal or behaviour data in order to quantify over-time trends.
- Apply the model in live pilot environments for its social as well as operating quantification of effect.

Overall, the project verifies not only the technical feasibility, but also the strategic value of machine learning to augment mental health training and in-workplace interventions. The technology has the potential to deliver healthy and balanced workplaces for the technology sector.

---
9. Rerefences

- Harnois, G. and Gabriel, P. (2002). *Mental health and work: Impact, issues and good practices*. World Health Organization.
- World Health Organization (2022). *Mental health: strengthening our response*. Available at: https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response .
- OSMI (2023). *Open Sourcing Mental Illness*. Available at: https://osmihelp.org/ [Accessed 25 Mar. 2025].
- Shatte, A.B.R., Hutchinson, D.M. y Teague, S.J. (2019). Machine learning in mental health: A scoping review of methods and applications. *Psychological Medicine*, 49(9), pp.1426–1448.
"""